Add playwright init configuration
firecamp-dev/firecamp pull request #130
Opened 2023-10-21 11:22 UTC by aggmoulik

2023-10-22 19:19 UTC, shreya-gr requested changes

2023-10-22 19:19 UTC, shreya-gr commented on e2e/example.spec.ts
> +  await expect(page).toHaveTitle(/Playwright/);
The first basic test would be

1. open firecamp.dev
2. open rest request playground
3. test json `https://jsonplaceholder.typicode.com/todos/1`
4. asset the response

2023-10-22 19:20 UTC, shreya-gr commented on .github/workflows/playwright.yml
> +  pull_request:
Can you please explain the workflow with short description in the PR?

2023-10-26 06:50 UTC, Nishchit14 commented
@aggmoulik any progress from your side? Other tasks are waiting to get this PR merge. please update your status.

2026-05-17 21:36 UTC, closed without merging